spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8 #本机mysql
   #url: jdbc:mysql://192.168.10.130/sell?characterEncoding=utf-8&useSSL=false #连接虚拟机
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null #返回值为null不返回
  freemarker:
    suffix: .ftl
server:
  servlet:
    context-path: /sell
  port: 8080
#swagger 开关
swagger2:
   enable: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: E:/log/lab.log
#  level: debug

#wechat:
#  mpAppId: xxxx
#  mpAppSecret: xxxx
#  mchId:
#  mchKey:
#  notifyUrl: http://ysell.natapp1.cc/sell/pay/notify
#  keyPath: #api证书路径
